# Service for the application
apiVersion: v1
kind: Service
metadata:
  name: go-web-app
  labels:
    app: go-web-app
spec:
  ports:
  - port: 80          # Port exposed by the service
    targetPort: 8080  # Port on the pod where the application is running
    protocol: TCP
  selector:
    app: go-web-app   # This selects the pods with this label
  type: ClusterIP     # Change to LoadBalancer if you want external access